source 'https://rubygems.org'
ruby '>= 3.3.0'

gem 'sinatra', '~> 4.0'
gem 'rackup'
gem 'webrick'   # rackup 2.2+ no longer bundles a web server

group :development, :test do
  gem 'cucumber'
  gem 'cucumber-sinatra'
  gem 'capybara'

  gem 'rspec'
  gem 'rspec-autotest'

  gem 'rack-test'

  gem 'byebug'
  gem 'launchy'
  gem 'rerun'
end
