source 'https://rubygems.org'
ruby '>= 2.7.8'

gem 'sinatra', '~> 4.0'
# gem 'rackup'

group :development, :test do
  gem 'cucumber'
  gem 'cucumber-sinatra'
  gem 'capybara'

  gem 'rspec'
  gem 'rspec-autotest'

  gem 'rack-test'

  gem 'byebug'
  gem 'launchy'
  gem 'rerun'
end
