#!/usr/bin/env ruby

require 'optparse'
require 'platform-api'
require 'yaml'
require 'csv'

def main()
  h = HerokuAppManager.new
  $opts = OptionParser.new do |opt|
    opt.banner = "Usage: #{__FILE__} [required options] [individual|team|delapps|delusers]
'individual' creates individual apps, 'team' creates team apps, 'delapps' deletes any apps with given prefix,
'delusers' deletes all users in CSV file from the team. 
Heroku team name and app prefix are always required.
CSV file is required when creating individual or team apps or deleting users.
It's safe to run multiple times, since existing apps/collaborators are left alone.

If HEROKU_API_KEY is set, it is used as the API token.
Otherwise, if you have logged into the Heroku CLI with 'heroku login', 
the token returned by 'heroku auth:token' is used.  Otherwise, error.
"
    opt.on('-cCSVFILE', '--csv=CSVFILE', 'CSV file containing at least "Team" and "Email" named columns') do |csv|
      h.read_teams_and_emails_from_csv(csv)
    end
    opt.on('-tTEAM', '--team=TEAM', 'Heroku team name that should own the apps') do |team|
      h.heroku_team = team
    end
    opt.on('-pPREFIX', '--prefix=PREFIX', 'App name prefix, eg "fa23" gives apps "fa23-01", "fa23-02", etc.') do |pfx|
      h.app_prefix = pfx + '-'
    end
    opt.on('-xEMAILS', '--extra-users=EMAILS', 'Comma-separated list of emails that should also be collaborators on apps') do |extra_users|
      h.extra_users = extra_users.split(/,/)
    end
    opt.on('-n', '--dry-run', "Print what would be done, but don't actually do anything") do
      h.dry_run = true
      STDERR.puts "Dry run mode: no changes will be made on Heroku, even if you confirm by typing YES"
    end
  end
  begin
    $opts.parse!
  rescue OptionParser::ParseError => e
    h.print_help_and_exit(e.message)
  end
  
  command = ARGV.pop
  case command
  when 'individual' then h.create_individual_apps
  when 'team' then h.create_team_apps
  when 'delapps' then h.delete_apps
  when 'delusers' then h.delete_users
  else h.print_help_and_exit
  end
end

class HerokuAppManager
  attr_accessor :heroku_team, :app_prefix, :extra_users, :dry_run
  attr_reader :error
  def initialize
    @error = ''
    @heroku_team = nil
    @app_prefix = nil
    @extra_users = []
    @dry_run = false
    @users = {} # email => sanitized leader part of email (eg: 'john.q+public@gmail.com' => 'johnqpublic')
    @teams = Hash.new {|hsh, key| hsh[key] = [] } # teamID => [email1, email2, ...]
    print_help_and_exit("Can't find an API token") unless (@key = HerokuAppManager.get_api_token)
    @heroku = PlatformAPI.connect_oauth(@key)
  end

  public

  def self.get_api_token
    if (key = ENV['HEROKU_API_KEY'])
      puts "Using HEROKU_API_KEY value as API token"
      return key
    end
    key = `heroku auth:token 2>/dev/null`.chomp
    if $?.exitstatus == 0
      puts "Using value of 'heroku auth:token' as API token"
      return key
    end
    STDERR.puts 'No HEROKU_API_KEY and not logged into Heroku CLI (try `heroku login`)'
    nil
  end

  def valid?
    @error << "Heroku team name is required\n" unless @heroku_team
    @error << "App prefix is required\n" unless @app_prefix
    @error == ''
  end

  def read_teams_and_emails_from_csv(csv)
    data = CSV.parse(IO.read(csv), headers: true)
    hash = data.first.to_h
    print_help_and_exit "Need at least 'Team' (int) and 'Email' (str) columns in #{csv}" unless
      hash.has_key?('Team') && hash.has_key?('Email')
    data.each do |row|
      email = row['Email']
      print_help_and_exit("Duplicate email in #{csv}: #{email}") if @users.has_key?(email) # duplicate!
      @users[email] = user_part_of_email(email)
      @teams[row['Team']] << email
    end
  end

  def create_individual_apps
    message = %Q{In Heroku team '#{@heroku_team}', create individual apps for #{@users.keys.length} students starting with #{@app_prefix}}
    message << %Q{and also add users: #{@extra_users.join(', ')}} unless @extra_users.empty?
    confirm(message)
    begin
      @users.each_pair do |email,sanitized_username|
        appname = "#{@app_prefix}#{sanitized_username}"
        existing_apps.include?(appname) ?
          check_add_collaborators(appname,[email]) :
          create_app_and_add_collaborators(appname, [email])
      rescue Excon::Error => e
        "Error creating/adding collaborator on #{appname}: #{e.inspect}"
      end
    end
  end

  def create_team_apps
    confirm(%Q{In Heroku team '#{@heroku_team}', create #{@teams.keys.length} team apps starting with #{@app_prefix} and also add users: #{@extra_users.join(', ')}})
    @teams.each_pair do |team_id, emails|
      # if team id is numeric, treat as number and zero-pad to 2 digits, else leave as is
      team_id = sprintf("%02d", team_id) if team_id =~ /^[0-9]+$/
      appname = "#{@app_prefix}#{team_id}"
      existing_apps.include?(appname) ?
        check_add_collaborators(appname, emails) :
        create_app_and_add_collaborators(appname, emails)
    end
  end

  def delete_apps
    apps_to_delete = existing_apps.select { |app| app =~ /^#{@app_prefix}/ }
    STDERR.puts("No apps named #{@app_prefix}* exist in team '#{@heroku_team}'") || exit(0) if apps_to_delete.empty?
    confirm(%Q{In Heroku team '#{@heroku_team}', delete #{apps_to_delete.length} apps named #{@app_prefix}*})
    apps_to_delete.each do |app|
      puts "delete #{app}"
      @heroku.app.delete(app) unless dry_run
    end
  end

  def delete_users
    confirm(%Q{In Heroku team '#{@heroku_team}', delete any of the #{@users.keys.length} users who appear in CSV file})
    existing_team_users = @heroku.team_member.list(@heroku_team)
    @users.keys.each do |user|
      if existing_team_users.include?(user)
        puts "remove #{user}"
        @heroku.team_member.delete(@heroku_team, user) unless dry_run
      else
        puts "  skip #{user}"
      end
    end
  end
  
  def print_help_and_exit(msg=nil)
    STDERR.puts "Error: #{msg}" if msg
    STDERR.puts $opts
    exit 1
  end

  def existing_apps
    @existing_apps ||= @heroku.team_app.list_by_team(@heroku_team).map { |app| app['name'] }
  end

  private

  def check_add_collaborators(appname, emails)
    puts "exists #{appname}"
    emails.each do |email|
      if @heroku.collaborator.list(appname).
           map { |c| c['user']['email'] }.
           include?(email)
        puts "  exists collaborator #{email}"
      else
        puts "  create collaborator #{email}"
        @heroku.collaborator.create(appname, { user: email, silent: true }) unless dry_run
      end
    end
  end

  def create_app_and_add_collaborators(appname, emails)
    puts "create #{appname}"
    @heroku.team_app.create(name: appname, team: @heroku_team, locked: true) unless dry_run
    puts "  create collaborators #{emails.join(', ')}"
    unless dry_run
      emails.each do |email|
        @heroku.collaborator.create(appname, { user: email, silent: true }) 
      end
    end
  end

  def user_part_of_email(email)
    puts "Email #{email} not valid" and exit 1 unless email =~ /^([^@]+)@([^@]+)$/
    $1.gsub(/[^A-Za-z0-9]/, '-')
  end

  def confirm(description)
    puts description
    puts "\nType YES (case-sensitive) to continue, anything else to abort:"
    exit 1 unless (STDIN.gets.chomp == "YES")
  end

end                             # class HerokuAppManager

main()
